# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfazNuevoProducto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nuevo_producto(object):
    def setupUi(self, nuevo_producto):
        nuevo_producto.setObjectName("nuevo_producto")
        nuevo_producto.resize(256, 272)
        self.verticalLayout = QtWidgets.QVBoxLayout(nuevo_producto)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(nuevo_producto)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.frame = QtWidgets.QFrame(nuevo_producto)
        self.frame.setStyleSheet("QFrame#frame{\n"
"border: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.input_codigo = QtWidgets.QLineEdit(self.frame)
        self.input_codigo.setMinimumSize(QtCore.QSize(0, 24))
        self.input_codigo.setPlaceholderText("")
        self.input_codigo.setObjectName("input_codigo")
        self.verticalLayout_2.addWidget(self.input_codigo)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.input_desc = QtWidgets.QLineEdit(self.frame)
        self.input_desc.setMinimumSize(QtCore.QSize(0, 24))
        self.input_desc.setPlaceholderText("")
        self.input_desc.setObjectName("input_desc")
        self.verticalLayout_2.addWidget(self.input_desc)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.input_precio = QtWidgets.QLineEdit(self.frame)
        self.input_precio.setMinimumSize(QtCore.QSize(0, 24))
        self.input_precio.setPlaceholderText("")
        self.input_precio.setObjectName("input_precio")
        self.verticalLayout_2.addWidget(self.input_precio)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.input_stock = QtWidgets.QLineEdit(self.frame)
        self.input_stock.setMinimumSize(QtCore.QSize(0, 24))
        self.input_stock.setPlaceholderText("")
        self.input_stock.setObjectName("input_stock")
        self.verticalLayout_2.addWidget(self.input_stock)
        self.verticalLayout.addWidget(self.frame)
        self.btn_nuevo_producto = QtWidgets.QPushButton(nuevo_producto)
        self.btn_nuevo_producto.setMinimumSize(QtCore.QSize(0, 34))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_nuevo_producto.setFont(font)
        self.btn_nuevo_producto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nuevo_producto.setObjectName("btn_nuevo_producto")
        self.verticalLayout.addWidget(self.btn_nuevo_producto)

        self.retranslateUi(nuevo_producto)
        QtCore.QMetaObject.connectSlotsByName(nuevo_producto)

    def retranslateUi(self, nuevo_producto):
        _translate = QtCore.QCoreApplication.translate
        nuevo_producto.setWindowTitle(_translate("nuevo_producto", "Ingresar datos"))
        self.label_5.setText(_translate("nuevo_producto", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Nuevo producto</span></p></body></html>"))
        self.label.setText(_translate("nuevo_producto", "Codigo"))
        self.label_2.setText(_translate("nuevo_producto", "Descripcion"))
        self.label_3.setText(_translate("nuevo_producto", "Precio unitario"))
        self.label_4.setText(_translate("nuevo_producto", "Stock"))
        self.btn_nuevo_producto.setText(_translate("nuevo_producto", "Cargar producto"))
